title: Andrei Polukhin's blog
email: andrei.polukhin.blog@gmail.com
description: |-
  Andrei is a philosopher in mind and a romantic in heart.
  He shares his experience coming from Ukraine and settling in Vienna,
  working as a software engineer and undergoing psychoanalysis. He thinks about life
  and is unabashedly honest with his readers. Enjoy ;)

url: "https://andrei-polukhin.github.io"

github_username: andrei-polukhin
linkedin_username: andrei-polukhin
instagram_username: andrewpolukhin
disqus:
  shortname: andrei-polukhin

theme: minima
favicon: "/assets/images/favicon.ico"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
